"""Initial migration.

Revision ID: 20859094996f
Revises: 
Create Date: 2025-04-30 00:02:12.970247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20859094996f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SUBSCRIBER', 'MANAGER', 'INTERN', name='userrole'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='userstatus'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
